### ISSUE TITLE
What is the license for this code

### ISSUE THREAD

**Issue by Alex-Butenko** [thomasclaudiushuber/Wpf-Grid-Extensions#1]
Hi Thomas!
This extension is avesome! However, I think, nobody will be able to use it without a licence. Can you please add license info?

**Comment by lindexi** [comment]
@thomasclaudiushuber Thank you. It is usefully. Can I use it in my business code?

**Comment by thomasclaudiushuber** [comment]
Hey @lindexi, yes, feel free to copy and use it. You don't have to add a reference to me or this repo.

@Alex-Butenko Hey Alex, sorry, I somehow missed the notification on this one, and the repo was meant as a sample, you should feel free to copy the code. I've added a license file. Thank you.

**Comment by lindexi** [comment]
@thomasclaudiushuber  Thank you
